My Sneaker Wish List/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MySneakerWishList.ViewModels;
using MySneakerWishList.Models;
using MySneakerWishList.Data;
using Microsoft.EntityFrameworkCore;

namespace MySneakerWishList.Controllers
{
    public class CategoryController : Controller
    {

        public IActionResult Index()
        {
            List<ShoeCategory> categories = context.Categories.ToList();
            return View(categories);

        }

        private readonly ShoeDbContext context;

        public CategoryController(ShoeDbContext dbContext)
        {
            context = dbContext;
        }

        public IActionResult Add()
        {
            AddCategoryViewModel addCategoryViewModel = new AddCategoryViewModel();
            return View(addCategoryViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddCategoryViewModel addCategoryViewModel)
        {
            if (ModelState.IsValid)
            {

                ShoeCategory newCategory = new ShoeCategory
                {
                    Name = addCategoryViewModel.Name

                };

                context.Categories.Add(newCategory);
                context.SaveChanges();

                return Redirect("/Category");
            }

            return View(addCategoryViewModel);
        }

    }
}

My Sneaker Wish List/Controllers/ShoeController.cs
using Microsoft.AspNetCore.Mvc;
using MySneakerWishList.Models;
using System.Collections.Generic;
using MySneakerWishList.ViewModels;
using MySneakerWishList.Data;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace MySneakerWishList.Controllers
{
    public class ShoeController : Controller
    {
        private ShoeDbContext context;

        public ShoeController(ShoeDbContext dbContext)
        {
            context = dbContext;
        }

        // GET: /<controller>/
        public IActionResult Index()
        {
             IList<Shoe> shoes = context.Shoes.Include(c => c.Category).ToList();
            
            return View(shoes);
        }

        public IActionResult Add()
        {
            var listOfCategories = context.Categories.ToList();
            AddShoeViewModel addShoeViewModel = new AddShoeViewModel(listOfCategories);
            return View(addShoeViewModel);
        }

        [HttpPost]
        public IActionResult Add(AddShoeViewModel addShoeViewModel)
        {
            if (ModelState.IsValid)
            {
                ShoeCategory catg = context.Categories.Single(s => s.ID == addShoeViewModel.CategoryID);
                // Add the new cheese to my existing cheeses
                Shoe Shoe = new Shoe
                {
                    Name = addShoeViewModel.Name,
                    Description = addShoeViewModel.Description,
                    Category = catg
                };

                context.Shoes.Add(Shoe);
                context.SaveChanges();

                return Redirect("/Shoe");
            }

            return View(addShoeViewModel);
        }

        public IActionResult Remove()
        {
            ViewBag.title = "Remove Shoes";
            ViewBag.shoes = context.Shoes.ToList();
            return View();
        }

        [HttpPost]
        public IActionResult Remove(int[] shoeIds)
        {
            foreach (int shoeId in shoeIds)
            {
                Shoe theShoe = context.Shoes.Single(c => c.ID == shoeId);
                context.Shoes.Remove(theShoe);
            }

            context.SaveChanges();

            return Redirect("/Shoe");
        }
    }
}

My Sneaker Wish List/Views/Category/Add.cshtml
@model MySneakerWishList.ViewModels.AddCategoryViewModel
@{
    ViewData["Title"] = "Add";
}

<h2>Add Category</h2>

<form asp-controller="Category" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name"></span>
    </div>
    <input type="submit" value="Create Category " />
</form>

My Sneaker Wish List/Views/Category/Index.cshtml
@model List<MySneakerWishList.Models.ShoeCategory>
@{
    ViewData["Title"] = "Index";
}

<h2>Categories</h2>

<p><a asp-controller="Category" asp-action="Add">Add Category</a></p>


<ul>

    @foreach (var category in Model)
    {
        <li>

            <a asp-controller="Shoe"
               asp-action="Category"
               asp-route-id="@category.ID">@category.Name</a>

        </li>


    }


</ul>